## Settings
title: Sulabh Chaturvedi
owner: "Sulabh Chaturvedi"
url: "https://sulabhchaturvedi.com"
baseurl: "/"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
twitter: "oSulabh"
github: "ChaturvediSulabh"
linkedin: "sulabh-chaturvedi-3b116288"
stackoverflow: "8600836"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
